# Generated by Django 5.1.6 on 2025-05-09 02:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConversationModel',
            fields=[
                ('conversation_id', models.CharField(max_length=36, primary_key=True, serialize=False, unique=True)),
                ('state', models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed')], default='OPEN', max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='MessageModel',
            fields=[
                ('event_type', models.CharField(max_length=17)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('msg_id', models.CharField(max_length=36, primary_key=True, serialize=False, unique=True)),
                ('content', models.TextField()),
                ('direction', models.CharField(choices=[('SENT', 'Sent'), ('RECEIVED', 'Received')], max_length=8)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='webhooks.conversationmodel')),
            ],
        ),
    ]
